from environment import TaskAllocationEnv
env = TaskAllocationEnv()
obs, _ = env.reset()
print("Obs shape:", obs.shape)
action = env.action_space.sample()
obs, reward, term, trunc, info = env.step(action)
print("Reward:", reward)
print("Tasks completed:", info["tasks_completed"])
print("Masks shape:", env.action_masks().shape)
print("All good!")