import json
from typing import List
from .registry import get_agent

def export_pipeline_json(agent_ids: List[str], pipeline_name: str = "My Pipeline") -> dict:
    """
    Exports a pipeline as a LangGraph-compatible JSON spec.
    """
    nodes = []
    edges = []

    agents = []
    for aid in agent_ids:
        a = get_agent(aid)
        if a:
            agents.append(a)

    for i, agent in enumerate(agents):
        nodes.append({
            "id": agent["id"],
            "name": agent["name"],
            "description": agent["description"],
            "input_type": agent["input_type"],
            "output_type": agent["output_type"],
            "step": i + 1
        })
        if i > 0:
            edges.append({
                "from": agents[i - 1]["id"],
                "to": agent["id"],
                "type": "sequential"
            })

    langgraph_spec = {
        "pipeline_name": pipeline_name,
        "version": "1.0",
        "framework": "langgraph",
        "graph": {
            "entry_point": agents[0]["id"] if agents else None,
            "nodes": nodes,
            "edges": edges,
            "finish": agents[-1]["id"] if agents else None
        },
        "python_template": _generate_python_template(agents)
    }

    return langgraph_spec

def _generate_python_template(agents: list) -> str:
    lines = [
        "# Auto-generated by AgentForge",
        "# Install: pip install langgraph langchain groq",
        "",
        "from langgraph.graph import StateGraph, END",
        "from typing import TypedDict",
        "",
        "class PipelineState(TypedDict):",
        "    input: str",
        "    output: str",
        "",
    ]

    for a in agents:
        fn = a["id"].replace("-", "_")
        lines += [
            f"def {fn}(state: PipelineState) -> PipelineState:",
            f"    # Agent: {a['name']}",
            f"    # TODO: implement {a['description']}",
            f"    output = state['input']  # replace with real logic",
            f"    return {{**state, 'output': output}}",
            "",
        ]

    lines += [
        "workflow = StateGraph(PipelineState)",
    ]

    for a in agents:
        fn = a["id"].replace("-", "_")
        lines.append(f"workflow.add_node('{a['id']}', {fn})")

    if agents:
        lines.append(f"workflow.set_entry_point('{agents[0]['id']}')")
        for i in range(len(agents) - 1):
            lines.append(f"workflow.add_edge('{agents[i]['id']}', '{agents[i+1]['id']}')")
        lines.append(f"workflow.add_edge('{agents[-1]['id']}', END)")

    lines += [
        "",
        "app = workflow.compile()",
        "result = app.invoke({'input': 'your input here', 'output': ''})",
        "print(result['output'])",
    ]

    return "\n".join(lines)
