#!/usr/bin/env python3
# Auto-generated by AgentForge — sklearn model wrapper
import sys
import os
import json

sys.stdout.reconfigure(encoding='utf-8')
sys.stdin.reconfigure(encoding='utf-8')

def main():
    raw = sys.stdin.read().strip()
    if not raw:
        print("No input provided. Send comma-separated numbers: sepal_length, sepal_width, petal_length, petal_width")
        return

    agent_dir = os.path.dirname(os.path.abspath(__file__))

    try:
        # Parse input — accept comma-separated or JSON array
        if raw.startswith('['):
            features = json.loads(raw)
        else:
            features = [float(x.strip().split(':')[-1]) for x in raw.split(',')]
    except Exception as e:
        print(f"Input error: {e}")
        print(f"Expected 4 comma-separated numbers: sepal_length, sepal_width, petal_length, petal_width")
        return

    if len(features) != 4:
        print(f"Expected 4 features, got {len(features)}")
        print(f"Input format: sepal_length, sepal_width, petal_length, petal_width")
        return

    try:
        import joblib as _jl
        model = _jl.load(os.path.join(agent_dir, 'model.pkl'))
        
        import joblib as _jl2
        scaler = _jl2.load(os.path.join(agent_dir, 'scaler.pkl'))
        features = scaler.transform([features])[0].tolist()
        result = model.predict([features])[0]
        task = "classification"
        class_labels = ['setosa', 'versicolor', 'virginica']

        print("=" * 36)
        print("  MODEL PREDICTION")
        print("=" * 36)
        feat_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
        for name, val in zip(feat_names, features):
            print(f"  {name:<20} {val}")
        print()
        if task == "classification":
            label = class_labels[int(result)] if class_labels and int(result) < len(class_labels) else str(result)
            print(f"  Prediction  : {label}")
            try:
                proba = model.predict_proba([features])[0]
                if class_labels and len(class_labels) == len(proba):
                    print(f"  Confidence  : {max(proba)*100:.1f}%")
                    print()
                    print("  Class probabilities:")
                    for lbl, p in zip(class_labels, proba):
                        bar = "#" * int(p * 20)
                        print(f"    {lbl:<16} {bar} {p*100:.1f}%")
                else:
                    print(f"  Confidence  : {max(proba)*100:.1f}%")
            except Exception:
                pass
        else:
            print(f"  Prediction  : {result:.4f}")
        print("=" * 36)

    except Exception as e:
        print(f"Model error: {e}")

if __name__ == "__main__":
    main()
